# """
# Django settings for Jardin project.

# Generated by 'django-admin startproject' using Django 6.0.6.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """

# from pathlib import Path
# import os
# import dj_database_url
# from datetime import timedelta
# from dotenv import load_dotenv
# load_dotenv()
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
# TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.getenv('SECRET_KEY')
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.getenv('DEBUG', 'False') == 'True'

# ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# # Application definition

# INSTALLED_APPS = [
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     'rest_framework',
#     'rest_framework_simplejwt',
#     'rest_framework_simplejwt.token_blacklist', 
#     'corsheaders',
#     'Jardin',
#     'plantes',
#     'reservations',
#     'users',
# ]

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]

# ROOT_URLCONF = "Jardin.urls"

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [TEMPLATES_DIR,os.path.join(BASE_DIR, 'plantes', 'templates')],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = "Jardin.wsgi.application"


# # Database
# # https://docs.djangoproject.com/en/6.0/ref/settings/#databases



# # # Configuration PostgreSQL
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': os.getenv('DB_NAME'),
# #         'USER': os.getenv('DB_USER'),
# #         'PASSWORD': os.getenv('DB_PASSWORD'),
# #         'HOST': os.getenv('DB_HOST', 'localhost'),
# #         'PORT': os.getenv('DB_PORT', '5432'),
# #     }
# # }

# # Configuration ENTIÈRE de la base de données en UNE ligne !
# DATABASES = {
#     'default': dj_database_url.config(default=os.getenv('DATABASE_URL'), conn_max_age=600)
# }

# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = "fr-fr"
# TIME_ZONE = "Africa/Douala"
# USE_L10N = True
# USE_I18N = True
# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/


# # Configuration des médias - Utiliser une URL relative
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# # Configuration des statics
# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# # Assurez-vous que ces répertoires existent
# os.makedirs(os.path.join(MEDIA_ROOT, 'plantes'), exist_ok=True)
# os.makedirs(os.path.join(MEDIA_ROOT, 'qr_codes'), exist_ok=True)


# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:8081",  # Pour Expo (par défaut)
#     # "http://127.0.0.1:8081",
#     "http://192.168.43.171::8081",  # Votre IP locale
#     # Pour les vrais appareils, ajoutez l'URL de l'API ou utilisez CORS_ALLOW_ALL_ORIGINS=True en développement
# ]

# # Si vous voulez tout autoriser en développement (déconseillé en production) :
# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_CREDENTIALS = True


# # settings.py
# REST_FRAMEWORK = {
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 10,  # 10 plantes par page par défaut
# }


# # ==================== EMAIL CONFIGURATION ====================
# EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
# EMAIL_HOST = os.getenv("EMAIL_HOST")
# EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
# EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')


# # ✅ Configuration REST Framework
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     ),
# }

# # ✅ Configuration JWT
# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
#     'ROTATE_REFRESH_TOKENS': True,
#     'BLACKLIST_AFTER_ROTATION': True,
#     'ALGORITHM': 'HS256',
#     'SIGNING_KEY': SECRET_KEY,
#     'VERIFYING_KEY': None,
#     'AUTH_HEADER_TYPES': ('Bearer',),
#     'USER_ID_FIELD': 'id',
#     'USER_ID_CLAIM': 'user_id',
#     'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
# }



# # Celery Configuration
# CELERY_BROKER_URL = os.getenv('REDIS_URL')  # URL de Redis
# CELERY_RESULT_BACKEND = os.getenv('REDIS_URL')
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'UTC'
# CELERY_TASK_TRACK_STARTED = True
# CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes


# # Utilisation de django-storages avec le protocole S3 de Supabase
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
# AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
# AWS_STORAGE_BUCKET_NAME = 'Mes medias'  # Le nom exact de votre bucket Supabase

# # L'endpoint fourni dans vos paramètres de stockage Supabase
# AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL') 

# # Paramètres de sécurité obligatoires
# AWS_S3_FILE_OVERWRITE = False
# AWS_DEFAULT_ACL = None
# AWS_QUERYSTRING_AUTH = False  # Permet d'avoir des URLs d'images directes et propres


"""
Django settings for Jardin project.
Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import os
import sys
import dj_database_url
from datetime import timedelta
from dotenv import load_dotenv

# ============================================
# GESTION DES ENVIRONNEMENTS
# ============================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Déterminer l'environnement
ENVIRONMENT = os.getenv('DJANGO_ENV', 'development')

# Charger le bon fichier .env
if ENVIRONMENT == 'production':
    env_file = BASE_DIR / '.env.prod'
else:
    env_file = BASE_DIR / '.env.dev'

if env_file.exists():
    load_dotenv(env_file)
    print(f"✅ Chargé: {env_file.name} (environnement: {ENVIRONMENT})")
else:
    load_dotenv()  # Fallback
    print(f"⚠️  Fichier {env_file.name} non trouvé, utilisation des variables système")

# ============================================
# SÉCURITÉ - PRODUCTION
# ============================================

SECRET_KEY = os.getenv('SECRET_KEY')

# En production, SECRET_KEY est OBLIGATOIRE
if not SECRET_KEY and ENVIRONMENT == 'production':
    raise ValueError("❌ SECRET_KEY non définie en production !")

DEBUG = os.getenv('DEBUG', 'False') == 'True'

# ✅ ALLOWED_HOSTS - Configuration dynamique pour Render
ALLOWED_HOSTS = ['*']  # Valeur par défaut pour développement

# Récupérer l'URL de Render automatiquement
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS = [RENDER_EXTERNAL_HOSTNAME, '.onrender.com']
    
# Ajouter les domaines personnalisés
CUSTOM_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
for host in CUSTOM_HOSTS:
    if host.strip():
        ALLOWED_HOSTS.append(host.strip())

# Supprimer les doublons
ALLOWED_HOSTS = list(set(ALLOWED_HOSTS))

# ============================================
# APPLICATIONS
# ============================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'storages',  # Pour S3/Supabase
    'Jardin',
    'plantes',
    'reservations',
    'users',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ✅ WhiteNoise pour les fichiers statiques
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Jardin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'plantes', 'templates')
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Jardin.wsgi.application"

# ============================================
# BASE DE DONNÉES - Supabase
# ============================================

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=ENVIRONMENT == 'production'  # ✅ SSL obligatoire pour Supabase
    )
}

# ============================================
# VALIDATION DES MOTS DE PASSE
# ============================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ============================================
# INTERNATIONALISATION
# ============================================

LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "Africa/Douala"
USE_I18N = True
USE_TZ = True

# ============================================
# FICHIERS STATIQUES ET MÉDIAS - WhiteNoise
# ============================================

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ✅ Configuration WhiteNoise pour les fichiers statiques
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Dossiers des fichiers statiques supplémentaires
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Fichiers médias
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Créer les dossiers nécessaires
os.makedirs(os.path.join(MEDIA_ROOT, 'plantes'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'qr_codes'), exist_ok=True)

# ============================================
# CORS - Configuration selon l'environnement
# ============================================

if ENVIRONMENT == 'production':
    # ✅ En production : liste blanche stricte
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS if origin.strip()]
    
    if not CORS_ALLOWED_ORIGINS:
        print("⚠️  Aucune origine CORS configurée en production !")
else:
    # En développement : plus permissif
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:8081",
        "http://127.0.0.1:8081",
        "http://localhost:8000",
    ]

CORS_ALLOW_CREDENTIALS = True

# ============================================
# REST FRAMEWORK
# ============================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# ============================================
# JWT - Configuration
# ============================================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# ============================================
# EMAIL
# ============================================

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# ============================================
# CELERY / REDIS
# ============================================

CELERY_BROKER_URL = os.getenv('REDIS_URL')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# ============================================
# STOCKAGE S3 (Supabase Storage)
# ============================================

AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')

# Vérifier la configuration S3 en production
if ENVIRONMENT == 'production':
    required_s3_vars = ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_STORAGE_BUCKET_NAME', 'AWS_S3_ENDPOINT_URL']
    missing = [var for var in required_s3_vars if not os.getenv(var)]
    if missing:
        print(f"⚠️  Variables S3 manquantes: {', '.join(missing)}")

# Configuration S3
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

# Utiliser S3 pour les médias en production
if ENVIRONMENT == 'production' and all([AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_STORAGE_BUCKET_NAME]):
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
else:
    # En développement, stockage local
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# ============================================
# SÉCURITÉ HTTPS - Production
# ============================================

if ENVIRONMENT == 'production':
    # ✅ Forcer HTTPS
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # ✅ HSTS (6 mois)
    SECURE_HSTS_SECONDS = 15768000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # ✅ Headers de sécurité
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # ✅ Cookies
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_HTTPONLY = True

# ============================================
# LOGGING
# ============================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if ENVIRONMENT == 'development' else 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO' if ENVIRONMENT == 'development' else 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if ENVIRONMENT == 'development' else 'ERROR',
            'propagate': False,
        },
    },
}

# ============================================
# VERIFICATION FINALE
# ============================================

if ENVIRONMENT == 'production':
    print("\n🔒 Configuration de production activée")
    print(f"✅ DEBUG: {DEBUG}")
    print(f"✅ ALLOWED_HOSTS: {ALLOWED_HOSTS}")
    print(f"✅ HTTPS forcé: {SECURE_SSL_REDIRECT}")
    print(f"✅ CORS restreint: {CORS_ALLOWED_ORIGINS}")
    print(f"✅ WhiteNoise activé pour les fichiers statiques")
    print("⚠️  Assurez-vous que toutes les variables d'environnement sont définies !")