# Generated by Django 6.0.6 on 2026-06-29 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=20)),
                (
                    "nombre_personnes",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "type_visite",
                    models.CharField(
                        choices=[
                            ("libre", "Visite Libre"),
                            ("guidee", "Visite Guidée Standard"),
                            ("scolaire", "Visite Scolaire"),
                            ("scientifique", "Visite Scientifique"),
                            ("privatisation", "Privatisation"),
                        ],
                        default="libre",
                        max_length=20,
                    ),
                ),
                ("date_visite", models.DateField()),
                ("heure_visite", models.TimeField()),
                (
                    "duree_estimee",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("confirmee", "Confirmée"),
                            ("annulee", "Annulée"),
                            ("terminee", "Terminée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=20, unique=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "ordering": ["-date_creation"],
            },
        ),
    ]
