# Generated by Django 6.0.6 on 2026-07-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="date_rappel",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="rappel_envoye",
            field=models.BooleanField(default=False),
        ),
    ]
