# Generated by Django 6.0.6 on 2026-06-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_scientifique",
                    models.CharField(
                        help_text="Nom latin unique.", max_length=255, unique=True
                    ),
                ),
                (
                    "nom_commun_fr",
                    models.CharField(
                        help_text="Nom usuel en français.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description accessible au grand public."
                    ),
                ),
                ("famille_botanique", models.CharField(max_length=255)),
                (
                    "zone_geographique",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "anecdote",
                    models.TextField(
                        blank=True,
                        help_text="Anecdote culturelle ou médicinale.",
                        null=True,
                    ),
                ),
                (
                    "image_principale",
                    models.ImageField(
                        help_text="Photo principale de la plante.", upload_to="plantes/"
                    ),
                ),
                (
                    "qr_code_url",
                    models.URLField(
                        blank=True,
                        help_text="URL unique de la fiche plante pour le QR Code.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        help_text="Image du QR Code générée.",
                        null=True,
                        upload_to="qr_codes/",
                    ),
                ),
                ("est_active", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
            ],
        ),
    ]
