# Generated by Django 6.0.6 on 2026-06-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Circuit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "duree_estimee",
                    models.CharField(
                        help_text="Ex: 2 heures, 1 journée", max_length=100
                    ),
                ),
                (
                    "points_interet",
                    models.TextField(
                        help_text="Liste des points d'intérêt séparés par des virgules"
                    ),
                ),
                (
                    "image_principale",
                    models.ImageField(blank=True, null=True, upload_to="circuits/"),
                ),
                ("est_active", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["titre"],
            },
        ),
    ]
