# Generated by Django 6.0.6 on 2026-06-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantes", "0002_circuit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abonne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nom", models.CharField(blank=True, max_length=100, null=True)),
                ("est_actif", models.BooleanField(default=True)),
                ("date_abonnement", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Abonné",
                "verbose_name_plural": "Abonnés",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("contenu", models.TextField()),
                (
                    "extrait",
                    models.CharField(
                        help_text="Résumé de l'article pour la liste", max_length=300
                    ),
                ),
                ("auteur", models.CharField(max_length=255)),
                (
                    "image_principale",
                    models.ImageField(blank=True, null=True, upload_to="blog/"),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("plante_du_mois", "🌿 Plante du mois"),
                            ("saison", "🌸 Saisons de floraison"),
                            ("actualite", "📰 Actualités scientifiques"),
                            ("decouverte", "🔬 Nouvelles découvertes"),
                            ("conseil", "💡 Conseils jardinage"),
                            ("evenement", "🎪 Événements"),
                        ],
                        default="actualite",
                        max_length=100,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags séparés par des virgules",
                        max_length=255,
                    ),
                ),
                ("est_publie", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("vues", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-date_publication"],
            },
        ),
    ]
