# Generated by Django 6.0.6 on 2026-06-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantes", "0003_abonne_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleVue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("date_vue", models.DateTimeField(auto_now_add=True)),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vues_detail",
                        to="plantes.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vue d'article",
                "verbose_name_plural": "Vues d'articles",
                "unique_together": {("article", "ip_address")},
            },
        ),
    ]
