# Generated by Django 6.0.6 on 2026-07-09 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantes", "0004_articlevue"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("facile", "🌱 Facile"),
                            ("moyen", "🌿 Moyen"),
                            ("difficile", "🌳 Difficile"),
                        ],
                        default="facile",
                        max_length=20,
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=10, help_text="Points attribués pour une bonne réponse"
                    ),
                ),
                (
                    "temps_estime",
                    models.PositiveIntegerField(
                        default=30, help_text="Temps estimé en secondes"
                    ),
                ),
                ("est_active", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["niveau", "date_creation"],
            },
        ),
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True,
                        help_text="ID utilisateur (pour plus tard)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("score_total", models.PositiveIntegerField(default=0)),
                ("questions_repondues", models.PositiveIntegerField(default=0)),
                ("bonnes_reponses", models.PositiveIntegerField(default=0)),
                (
                    "niveau_actuel",
                    models.CharField(
                        choices=[
                            ("facile", "🌱 Facile"),
                            ("moyen", "🌿 Moyen"),
                            ("difficile", "🌳 Difficile"),
                        ],
                        default="facile",
                        max_length=20,
                    ),
                ),
                ("est_termine", models.BooleanField(default=False)),
                ("date_debut", models.DateTimeField(auto_now_add=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Session de quiz",
                "verbose_name_plural": "Sessions de quiz",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="QuizOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.CharField(max_length=255)),
                ("est_correcte", models.BooleanField(default=False)),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="plantes.quizquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="QuizReponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("est_correcte", models.BooleanField(default=False)),
                (
                    "temps_reponse",
                    models.PositiveIntegerField(
                        default=0, help_text="Temps de réponse en secondes"
                    ),
                ),
                ("date_reponse", models.DateTimeField(auto_now_add=True)),
                (
                    "option_choisie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantes.quizoption",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantes.quizquestion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="plantes.quizsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse",
                "verbose_name_plural": "Réponses",
            },
        ),
    ]
